spring:
  application:
    name: user-center
  web:
    error:
      include-stacktrace: always
      include-message: always
      include-exception: true
  datasource:
    url: jdbc:mysql://localhost:3306/euler_uc
    username: root
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
  messages:
    basename: classpath*:language/**/*
    use-code-as-default-message: true
  security:
    oauth2:
      authorizationserver:
        client:
          default:
            require-proof-key: true
            require-authorization-consent: true
            registration:
              client-id: default
              client-authentication-methods: none
              authorization-grant-types:
                - authorization_code
              scopes:
                - openid
              redirect-uris:
                - https://example.com/code
            token:
              access-token-time-to-live: 7d
          admin:
            require-proof-key: true
            registration:
              client-id: admin
              client-secret: '{noop}admin'
              client-authentication-methods:
                - client_secret_basic
              authorization-grant-types:
                - authorization_code
                - refresh_token
              redirect-uris:
                - https://example.com/auth/callback
              scopes:
                - openid
                - profile
                - email
                - phone
                - authorities
              post-logout-redirect-uris:
                - https://example.com
            token:
              access-token-time-to-live: 5m
              refresh-token-time-to-live: 7d
              reuse-refresh-tokens: false

euler:
  application:
    runtime-path: @basedir@/var/run
    temp-path: @basedir@/var/tmp
  copyright:
    holder:
      website: 'https://www.eulerproject.io'
      name: 'Euler Projects'
  web:
    site:
      name: 'Euler Projects'
    page:
      show-stack-trace: true
  security:
    web:
      enabled: true
      endpoint:
        csrf:
          enabled: true
        user:
          login-page: /signin
          login-processing-url: /doLogin
          logout-page: /signout
          logout-processing-url: /doLogout
        password:
          enabled: true
          change-password-page: /change-pw
          change-password-processing-url: /doChangePw
        signup:
          enabled: true
          signup-page: /create-account
          signup-processing-url: /doSignup
    oauth2:
      authorizationserver:
        authorization-store-type: redis
        redis-key-prefix: 'euler:oauth2:auth'
        dynamic-client-registration:
          enabled: true
        apple-app-attest:
          enabled: true
          auto-create-user-if-not-exists: true
          allow-development-environment: true
          apps:
            app-attest-demo:
              team-id: 2LP82WL749
              bundle-id: org.eulerframework.AppAttestDemo
      resourceserver:
        url-patterns:
          - /api/**
