version: '3'
services:
  mysql:
    image: mysql:5.6.40
    #restart: always
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - ./volumes/mysql/external:/external
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /external/root-passwd

  redis:
    image: redis:4.0.10
    #restart: always
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --appendonly yes

  app-demo:
    image: eulerproject/demo:1.0.0
    volumes:
      - ./volumes/app-demo:/var/lib/euler-framework
    links:
      - mysql
      - redis
    ports:
      - "8080:8080"
