import Foundation

// MARK: - Models

struct AttestRegistrationResponse: Codable {
    let kid: String
    let sub: String
}

// MARK: - AppAttestRegistrationService

/// Handles App Attestation registration (Phase 1) — this is NOT part of the OAuth flow.
///
/// The registration process establishes a hardware-backed identity for this specific app instance
/// on this specific device. The keyId is generated by the Secure Enclave via `DCAppAttestService`
/// and is intrinsically bound to both the app (identified by teamId.bundleId) and the physical device.
/// Once registered, the server records the corresponding public key and creates an anonymous user
/// tied to this keyId. Re-registration will generate a new keyId and create a new user — the
/// previous user data becomes inaccessible.
///
/// Endpoints used:
/// - `POST /app_attest/challenge` — obtain a one-time challenge for the Attestation flow
/// - `POST /app_attest/register`  — submit the Attestation Object to register the client
class AppAttestRegistrationService {
    static let shared = AppAttestRegistrationService()

    /// Base URL is shared with OAuthTokenManager via the same UserDefaults key
    private var base: String {
        var result = UserDefaults.standard.string(forKey: OAuthTokenManager.baseUrlKey)
            ?? OAuthTokenManager.defaultBaseUrl
        while result.hasSuffix("/") {
            result.removeLast()
        }
        return result
    }
    private var challengeEndpoint: String { base + "/app_attest/challenge" }
    private var registerEndpoint: String { base + "/app_attest/register" }

    /// Last HTTP request/response debug info (for log display in the UI)
    private(set) var lastRequestInfo: RequestInfo?
    private(set) var lastResponseInfo: ResponseInfo?

    /// Clear request/response debug info before each new operation to avoid stale data
    func clearLastRequestInfo() {
        lastRequestInfo = nil
        lastResponseInfo = nil
    }

    private init() {}

    /// Fetch a one-time challenge for the Attestation flow.
    /// Endpoint: `POST /app_attest/challenge` — no authentication, no request body required.
    /// - Returns: A one-time challenge string (Base64URL-encoded, valid for 5 minutes, single-use)
    func fetchChallenge() async throws -> String {
        guard let url = URL(string: challengeEndpoint) else {
            throw AppAttestError.invalidURL
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"

        lastRequestInfo = RequestInfo(request: request)

        let (data, response) = try await URLSession.shared.data(for: request)
        let httpResponse = response as? HTTPURLResponse
        let rawBody = String(data: data, encoding: .utf8) ?? "<binary data>"
        lastResponseInfo = ResponseInfo(
            statusCode: httpResponse?.statusCode ?? -1,
            body: rawBody
        )

        guard let httpResponse = httpResponse, httpResponse.statusCode == 200 else {
            throw AppAttestError.serverError(
                statusCode: httpResponse?.statusCode ?? -1,
                error: "challenge_request_failed",
                description: rawBody
            )
        }

        let json = try JSONDecoder().decode([String: String].self, from: data)
        guard let challenge = json["challenge"] else {
            throw AppAttestError.invalidResponse
        }
        return challenge
    }

    /// Perform the full App Attestation registration (Phase 1).
    ///
    /// This should only be executed once during the initial setup. After successful registration,
    /// subsequent token requests use the Assertion flow (Phase 2) via `OAuthTokenManager`.
    ///
    /// The keyId produced by `DCAppAttestService.generateKey()` is bound to this specific app
    /// on this specific device — it is not transferable. Each attestation generates a new key;
    /// reusing an already-attested key will fail with `com.apple.devicecheck.error`.
    ///
    /// Flow: fetch attest challenge → generate key → generate attestation → submit registration
    /// - Returns: `AttestRegistrationResponse` containing the keyId and the anonymous user subject
    func register() async throws -> AttestRegistrationResponse {
        let attestManager = AppAttestManager.shared

        guard attestManager.isSupported else {
            throw AppAttestError.notSupported
        }

        // 1. Fetch a one-time challenge for the Attestation flow
        let challenge = try await fetchChallenge()

        // 2. Generate a new key for each Attestation attempt
        // ⚠️ A key can only be attested once; reusing an already-attested key
        //    will fail with com.apple.devicecheck.error
        let keyId = try await attestManager.generateNewKeyId()

        // 3. Generate the Attestation Object using the Apple API
        let attestation = try await attestManager.generateAttestation(
            keyId: keyId,
            challenge: challenge
        )

        // 4. Submit the registration request to the server
        guard let url = URL(string: registerEndpoint) else {
            throw AppAttestError.invalidURL
        }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/x-www-form-urlencoded", forHTTPHeaderField: "Content-Type")

        let params: [String: String] = [
            "kid": keyId,
            "attestation": attestation,
            "challenge": challenge
        ]

        // Use strict percent-encoding: .urlQueryAllowed does NOT encode +/= characters,
        // which would break form-urlencoded parsing (+ means space, = is a separator)
        var formUrlEncodingAllowed = CharacterSet.alphanumerics
        formUrlEncodingAllowed.insert(charactersIn: "-._~")
        let bodyString = params.map { "\($0.key)=\($0.value.addingPercentEncoding(withAllowedCharacters: formUrlEncodingAllowed) ?? $0.value)" }
            .joined(separator: "&")
        request.httpBody = bodyString.data(using: .utf8)

        lastRequestInfo = RequestInfo(request: request)

        let (data, response) = try await URLSession.shared.data(for: request)
        let httpResponse = response as? HTTPURLResponse
        let rawBody = String(data: data, encoding: .utf8) ?? "<binary data>"
        lastResponseInfo = ResponseInfo(
            statusCode: httpResponse?.statusCode ?? -1,
            body: rawBody
        )

        guard let httpResponse = httpResponse else {
            throw AppAttestError.invalidResponse
        }

        if httpResponse.statusCode == 200 {
            let result = try JSONDecoder().decode(AttestRegistrationResponse.self, from: data)
            // 5. Only persist the keyId to Keychain after the server has verified the attestation.
            //    The keyId is bound to this specific app instance on this specific device
            //    (generated by the Secure Enclave); losing it means losing access to the
            //    associated anonymous user, and re-registration creates a new identity.
            attestManager.saveKeyId(keyId)
            return result
        } else {
            let errorResponse = try? JSONDecoder().decode(OAuthErrorResponse.self, from: data)
            throw AppAttestError.serverError(
                statusCode: httpResponse.statusCode,
                error: errorResponse?.error ?? "registration_failed",
                description: errorResponse?.errorDescription
            )
        }
    }
}
