import DeviceCheck
import Foundation
import CryptoKit

/// Wrapper around Apple's `DCAppAttestService` for App Attest operations.
///
/// All keys generated by this service are bound to a specific app instance on a specific device:
/// the Secure Enclave creates a unique key pair identified by keyId, which is intrinsically tied
/// to both the app identity (teamId.bundleId) and the physical device hardware. This means:
/// - The keyId cannot be transferred to another device or another app
/// - Losing the keyId means losing the associated server-side identity
/// - Re-generating a key creates an entirely new identity
class AppAttestManager {
    static let shared = AppAttestManager()
    
    private let service = DCAppAttestService.shared
    
    /// Keychain storage key for the keyId.
    /// ⚠️ The keyId identifies the App Attest key pair in the Secure Enclave, which is bound
    /// to this specific app on this specific device. It MUST be stored in Keychain because:
    /// 1. Leaking the keyId could enable device identity spoofing or replay attacks
    /// 2. UserDefaults stores data as plaintext plist, readable on jailbroken devices
    private let keyIdKeychainKey = "com.app.appAttest.keyId"
    
    private init() {}
    
    /// Check whether App Attest is supported on the current device
    var isSupported: Bool {
        service.isSupported
    }
    
    /// Retrieve the stored keyId for the Assertion flow.
    /// The keyId uniquely identifies this app-on-device combination on the server.
    /// - Returns: The stored keyId, or nil if no registration has been completed
    func getExistingKeyId() -> String? {
        return KeychainHelper.shared.read(forKey: keyIdKeychainKey)
    }

    /// Generate a new App Attest key for the Attestation flow.
    /// The key is created in the Secure Enclave and is bound to this specific app on this
    /// specific device — it cannot be exported, transferred, or reused across installations.
    /// ⚠️ Each key can only be attested once, so a new key must be generated for each
    /// Attestation attempt. The keyId is NOT persisted to Keychain here — it should only
    /// be saved after the full Attestation flow (including server verification) succeeds.
    func generateNewKeyId() async throws -> String {
        return try await service.generateKey()
    }

    /// Persist the keyId to Keychain after the Attestation flow has fully succeeded.
    /// This keyId represents this app-on-device identity on the server.
    func saveKeyId(_ keyId: String) {
        _ = KeychainHelper.shared.save(keyId, forKey: keyIdKeychainKey)
    }
    
    /// Generate an Attestation Object for initial registration.
    /// - Parameters:
    ///   - keyId: The App Attest key identifier (bound to this app on this device)
    ///   - challenge: One-time challenge string from the server
    /// - Returns: Base64-encoded Attestation Object
    func generateAttestation(keyId: String, challenge: String) async throws -> String {
        let challengeData = Data(challenge.utf8)
        let challengeHash = Data(SHA256.hash(data: challengeData))
        let attestation = try await service.attestKey(keyId, clientDataHash: challengeHash)
        return attestation.base64EncodedString()
    }

    /// Generate an Assertion Object for re-authentication of a registered client.
    /// - Parameters:
    ///   - keyId: The App Attest key identifier (bound to this app on this device)
    ///   - challenge: One-time challenge string from the server
    /// - Returns: Base64-encoded Assertion Object
    func generateAssertion(keyId: String, challenge: String) async throws -> String {
        let challengeData = Data(challenge.utf8)
        let challengeHash = Data(SHA256.hash(data: challengeData))
        let assertion = try await service.generateAssertion(keyId, clientDataHash: challengeHash)
        return assertion.base64EncodedString()
    }
}
