import {useEffect, useState, useCallback} from 'react';
import {useParams} from 'react-router';
import {App as AntdApp, Button, Card, Empty, Tabs, Modal, Select, Space, Tag, Tooltip, Typography} from 'antd';
import type {TableProps, TabsProps} from 'antd';
import {EyeOutlined, EyeInvisibleOutlined, GoogleOutlined} from '@ant-design/icons';
import {useTranslation} from 'react-i18next';

import {DataTable} from '@/components/DataTable';
import {DetailLayout} from '@/components/DetailLayout';
import {InfoDescriptions} from '@/components/InfoDescriptions';
import type {InfoFieldDescriptor} from '@/components/InfoDescriptions';
import {fmtDateTime, dateTimeColumnWidth} from '@/i18n/datetime';
import {
    CopyableCell,
    MiddleEllipsisText,
    RowActions,
    computeActionsColumnWidth,
} from './_shared/tableLayout';
import {apiGet, apiPut, apiDelete, extractApiError} from './_shared/api';

/** A granted role/authority on a user. */
interface Authority {
    authority: string;
    name?: string;
}

/** One bound identity record (phone / email / google) of a user. */
interface Identity {
    identityId: string;
    identityType: string;
    phone?: string;
    email?: string;
    boundAt?: string;
    picture?: string;
    name?: string;
    emailVerified?: boolean;
    givenName?: string;
    familyName?: string;
}

/** The user basic-info projection returned by the list endpoint. */
interface UserRow {
    userId: string;
    username: string;
    authorities?: Authority[];
    enabled?: boolean;
    accountNonExpired?: boolean;
    accountNonLocked?: boolean;
    credentialsNonExpired?: boolean;
}

const UserDetail = () => {
    const {t} = useTranslation();
    // `<App>` context comes from AntdAppRoute (see router.tsx), so the
    // page needs no message holder of its own.
    const {message} = AntdApp.useApp();
    const {userId = ''} = useParams();
    // Breadcrumb is auto-generated by ConsoleLayout from the route's
    // `handle.title` (see router.tsx); the username is surfaced as the
    // DetailLayout page title instead. Call `usePageTitle(...)` from
    // @/layout/_shared/pageTitle if the breadcrumb itself should ever
    // carry the entity name.
    const [user, setUser] = useState<UserRow | null>(null);
    const [userLoading, setUserLoading] = useState(true);
    const [identities, setIdentities] = useState<Identity[]>([]);
    const [identitiesLoading, setIdentitiesLoading] = useState(false);
    const [revealedRawValues, setRevealedRawValues] = useState<Record<string, string>>({});  // identityId -> rawValue
    const [addAuthorityOpen, setAddAuthorityOpen] = useState(false);
    const [newAuthority, setNewAuthority] = useState<string | null>(null);

    // Load user basic info
    const loadUser = useCallback(() => {
        apiGet<UserRow[]>(`/admin/api/users?offset=0&limit=100`).then(users => {
            const found = (users || []).find(u => u.userId === userId);
            if (found) setUser(found);
            setUserLoading(false);
        }).catch(() => setUserLoading(false));
    }, [userId]);

    // Load identities
    const loadIdentities = useCallback(() => {
        setIdentitiesLoading(true);
        apiGet<Identity[]>(`/admin/api/users/${encodeURIComponent(userId)}/identities`).then(data => {
            setIdentities(data || []);
            setIdentitiesLoading(false);
        }).catch(() => setIdentitiesLoading(false));
    }, [userId]);

    useEffect(() => {
        loadUser();
        loadIdentities();
    }, [loadUser, loadIdentities]);

    // --- Identity actions ---
    const handleToggleRaw = async (identityId: string, fieldName: string) => {
        if (revealedRawValues[identityId]) {
            // Hide
            setRevealedRawValues(prev => {
                const next = {...prev};
                delete next[identityId];
                return next;
            });
        } else {
            // Reveal
            const result = await apiGet<{rawValue: string}>(
                `/admin/api/users/${encodeURIComponent(userId)}/identities/${encodeURIComponent(identityId)}/raw-fields/${fieldName}`
            );
            if (result) {
                setRevealedRawValues(prev => ({...prev, [identityId]: result.rawValue}));
            }
        }
    };

    const handleDeleteIdentity = async (identityId: string) => {
        try {
            await apiDelete(`/admin/api/users/${encodeURIComponent(userId)}/identities/${encodeURIComponent(identityId)}`);
            message.success(t('common.deleted'));
            loadIdentities();
        } catch (err) {
            message.error(extractApiError(err));
        }
    };

    // --- Authority actions ---
    const handleAddAuthority = async () => {
        if (!newAuthority || !user) return;
        const currentAuthorities = (user.authorities || []).map(a => a.authority);
        if (currentAuthorities.includes(newAuthority)) {
            setAddAuthorityOpen(false);
            return;
        }
        const updated = [...currentAuthorities, newAuthority];
        try {
            await apiPut(`/admin/api/users/${encodeURIComponent(userId)}`, {
                ...user,
                authorities: updated.map(a => ({authority: a})),
            });
            setAddAuthorityOpen(false);
            setNewAuthority(null);
            loadUser();
        } catch (err) {
            message.error(extractApiError(err));
        }
    };

    const handleRemoveAuthority = async (authority: string) => {
        if (!user) return;
        const updated = (user.authorities || [])
            .map(a => a.authority)
            .filter(a => a !== authority);
        try {
            await apiPut(`/admin/api/users/${encodeURIComponent(userId)}`, {
                ...user,
                authorities: updated.map(a => ({authority: a})),
            });
            loadUser();
        } catch (err) {
            message.error(extractApiError(err));
        }
    };

    // Shared column geometry: datetime columns hug their locale-formatted
    // content, action columns hug their labels.
    const boundAtColumnWidth = dateTimeColumnWidth();
    const identityActionWidth = computeActionsColumnWidth([t('user.delete')]);
    const authorityActionWidth = computeActionsColumnWidth([t('user.detailPage.removeAuthority')]);

    /** Masked value + reveal/hide affordance, shared by phone and email. */
    const renderMaskedValue = (fieldName: 'phone' | 'email') =>
        (masked: string | undefined, record: Identity) => {
            const revealed = revealedRawValues[record.identityId];
            return (
                <Space>
                    <span style={{fontFamily: 'monospace'}}>{revealed || masked}</span>
                    <Tooltip title={revealed ? t('user.detailPage.hideRaw') : t('user.detailPage.viewRaw')}>
                        <a onClick={() => handleToggleRaw(record.identityId, fieldName)}>
                            {revealed ? <EyeInvisibleOutlined/> : <EyeOutlined/>}
                        </a>
                    </Tooltip>
                </Space>
            );
        };

    /** Identity-id cell: opaque identifier, so copyable + middle-elided. */
    const identityIdColumn = {
        title: t('user.detailPage.identityId'),
        dataIndex: 'identityId',
        width: 320,
        render: (identityId: string) => (
            <CopyableCell
                mono
                value={identityId}
                display={(v) => <MiddleEllipsisText text={v} mono/>}
            />
        ),
    };

    const boundAtColumn = {
        title: t('user.detailPage.boundAt'),
        dataIndex: 'boundAt',
        width: boundAtColumnWidth,
        render: (val: string | null) => fmtDateTime(val),
    };

    const identityActionColumn = {
        title: t('user.column.action'),
        key: 'action',
        width: identityActionWidth,
        fixed: 'right' as const,
        render: (_: unknown, record: Identity) => (
            <RowActions
                columnWidth={identityActionWidth}
                actions={[
                    {
                        key: 'delete',
                        label: t('user.delete'),
                        danger: true,
                        onClick: () => void handleDeleteIdentity(record.identityId),
                    },
                ]}
            />
        ),
    };

    // --- Phone identities table ---
    const phoneIdentities = identities.filter(i => i.identityType === 'phone');

    const phoneColumns: TableProps<Identity>['columns'] = [
        identityIdColumn,
        {
            title: t('user.detailPage.phone'),
            // No width: the flexible column absorbing leftover space.
            dataIndex: 'phone',
            render: renderMaskedValue('phone'),
        },
        boundAtColumn,
        identityActionColumn,
    ];

    // --- Email identities table ---
    const emailIdentities = identities.filter(i => i.identityType === 'email');

    const emailColumns: TableProps<Identity>['columns'] = [
        identityIdColumn,
        {
            title: t('user.detailPage.email'),
            // No width: the flexible column absorbing leftover space.
            dataIndex: 'email',
            render: renderMaskedValue('email'),
        },
        boundAtColumn,
        identityActionColumn,
    ];

    // --- Google identities table ---
    const googleIdentities = identities.filter(i => i.identityType === 'google');

    const googleColumns: TableProps<Identity>['columns'] = [
        {
            title: t('user.detailPage.google.avatar'),
            dataIndex: 'picture',
            width: 60,
            render: (url) => url
                ? <img src={url} alt="avatar" style={{width: 32, height: 32, borderRadius: '50%'}}/>
                : '-',
        },
        {title: t('user.detailPage.google.name'), dataIndex: 'name', width: 150, ellipsis: true},
        {
            title: t('user.detailPage.google.email'),
            // No width: the flexible column absorbing leftover space.
            dataIndex: 'email',
            ellipsis: true,
        },
        {
            title: t('user.detailPage.google.emailVerified'),
            dataIndex: 'emailVerified',
            width: 100,
            render: (val) => val === true ? t('common.yes') : val === false ? t('common.no') : '-',
        },
        {title: t('user.detailPage.google.givenName'), dataIndex: 'givenName', width: 120, ellipsis: true},
        {title: t('user.detailPage.google.familyName'), dataIndex: 'familyName', width: 120, ellipsis: true},
        boundAtColumn,
        identityActionColumn,
    ];

    /** Every identity tab is the same table shape over a filtered slice. */
    const identityTable = (
        columns: TableProps<Identity>['columns'],
        dataSource: Identity[],
    ) => (
        <DataTable<Identity>
            onRefresh={() => loadIdentities()}
            columns={columns}
            dataSource={dataSource}
            rowKey="identityId"
            loading={identitiesLoading}
            pagination={false}
            locale={{emptyText: t('user.detailPage.noIdentities')}}
            flexFloor={220}
        />
    );

    const identityTabs: TabsProps['items'] = [
        {
            key: 'phone',
            label: t('user.detailPage.phone'),
            children: identityTable(phoneColumns, phoneIdentities),
        },
        {
            key: 'email',
            label: t('user.detailPage.email'),
            children: identityTable(emailColumns, emailIdentities),
        },
        {
            key: 'google',
            label: <span><GoogleOutlined style={{marginRight: 4}}/>Google</span>,
            children: identityTable(googleColumns, googleIdentities),
        },
    ];

    // --- Authorities table ---
    const authorityColumns: TableProps<Authority>['columns'] = [
        {
            title: t('user.detailPage.authorityName'),
            // No width: the flexible column absorbing leftover space.
            dataIndex: 'authority',
            render: (val) => {
                const key = `user.role.${val}`;
                const translated = t(key);
                return translated === key ? val : `${translated} (${val})`;
            },
        },
        {
            title: t('user.column.action'),
            key: 'action',
            width: authorityActionWidth,
            fixed: 'right',
            render: (_, record) => (
                <RowActions
                    columnWidth={authorityActionWidth}
                    actions={[
                        {
                            key: 'remove',
                            label: t('user.detailPage.removeAuthority'),
                            danger: true,
                            onClick: () => void handleRemoveAuthority(record.authority),
                        },
                    ]}
                />
            ),
        },
    ];

    if (userLoading) {
        return <Typography.Text>{t('common.loading')}</Typography.Text>;
    }
    // Loaded but absent: `loadUser` scans the list endpoint, so a user
    // outside the fetched window (or a failed request — apiGet resolves
    // null on non-2xx) lands here. antd's Empty carries a locale-aware
    // "no data" caption, so this needs no dedicated copy.
    if (!user) {
        return <Empty/>;
    }

    // Basic Info declared as Table-column-like descriptors over the user
    // record. Every field is mutated through the dedicated actions on the
    // user list page (create / reset password / enable / disable), so none
    // is inline-editable here.
    const fields: InfoFieldDescriptor<UserRow>[] = [
        {
            title: t('user.form.username'),
            dataIndex: 'username',
            render: (v) => (v ? <CopyableCell mono value={String(v)}/> : '—'),
        },
        {
            title: t('user.column.status'),
            dataIndex: 'enabled',
            render: (_, record) => {
                if (!record.enabled) {
                    return <Tag>{t('user.status.disabled')}</Tag>;
                }
                const flags: string[] = [];
                if (!record.accountNonExpired) flags.push(t('user.status.accountExpired'));
                if (!record.accountNonLocked) flags.push(t('user.status.accountLocked'));
                if (!record.credentialsNonExpired) flags.push(t('user.status.credentialsExpired'));
                if (flags.length === 0) {
                    return <Tag color="green">{t('user.status.normal')}</Tag>;
                }
                return (
                    <Space size={4} wrap>
                        {flags.map((f) => <Tag key={f} color="red">{f}</Tag>)}
                    </Space>
                );
            },
        },
    ];

    return (
        <DetailLayout title={user.username}>
            {/* Section: Basic Info — data-driven InfoDescriptions. */}
            <Card title={t('user.detailPage.basicInfo')} size="small">
                <InfoDescriptions dataSource={user} fields={fields}/>
            </Card>

            {/* Section: User Identities — one table per identity type. */}
            <Card title={t('user.detailPage.identities')} size="small">
                <Tabs items={identityTabs}/>
            </Card>

            {/* Section: User Authorities. */}
            <Card title={t('user.detailPage.authorities')} size="small">
                <DataTable<Authority>
                    leading={
                        <Button type="primary" onClick={() => setAddAuthorityOpen(true)}>
                            {t('user.detailPage.addAuthority')}
                        </Button>
                    }
                    onRefresh={() => loadUser()}
                    columns={authorityColumns}
                    dataSource={user.authorities || []}
                    rowKey="authority"
                    pagination={false}
                    flexFloor={220}
                />
            </Card>

            {/* Add authority modal */}
            <Modal
                title={t('user.detailPage.addAuthority')}
                open={addAuthorityOpen}
                onOk={handleAddAuthority}
                onCancel={() => { setAddAuthorityOpen(false); setNewAuthority(null); }}
                okText={t('common.ok')}
                cancelText={t('common.cancel')}
            >
                <Select
                    style={{width: '100%'}}
                    placeholder={t('user.detailPage.selectAuthority')}
                    value={newAuthority}
                    onChange={setNewAuthority}
                    options={[
                        {label: t('user.role.user'), value: 'user'},
                        {label: t('user.role.admin'), value: 'admin'},
                    ]}
                />
            </Modal>
        </DetailLayout>
    );
};

export default UserDetail;
